# Generated by Django 4.0.3 on 2022-05-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
