# Generated by Django 4.0.3 on 2022-05-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_remove_user_name_user_f_name_user_l_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='f_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
