# Generated by Django 4.0.4 on 2022-05-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_alter_user_f_name_alter_user_l_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('u', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurance.user')),
            ],
        ),
    ]
