# Generated by Django 4.0.4 on 2022-05-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
