# Generated by Django 4.0.4 on 2022-05-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='insurance',
        ),
    ]
