# Generated by Django 4.0.4 on 2022-05-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_delete_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=70)),
                ('p_type', models.CharField(max_length=20)),
                ('p_entry_age_min', models.PositiveIntegerField()),
                ('p_entry_age_max', models.PositiveIntegerField()),
                ('p_term_min', models.IntegerField()),
                ('p_term_max', models.IntegerField()),
                ('sum_assured_min', models.IntegerField()),
            ],
            options={
                'db_table': 'Policy',
            },
        ),
    ]
