# Generated by Django 4.0.4 on 2022-05-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_policy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='policy',
            table=None,
        ),
    ]
