# Generated by Django 4.0.4 on 2022-05-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_alter_policy_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Policy',
            new_name='term_insurance',
        ),
    ]
