# Generated by Django 4.0.4 on 2022-05-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0014_alter_term_insurance_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term_insurance',
            old_name='sum_assured_min',
            new_name='p_sum_assured_min',
        ),
    ]
