# Generated by Django 4.0.4 on 2022-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_rename_sum_assured_min_term_insurance_p_sum_assured_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='term_insurance',
            name='p_maturity_age',
            field=models.IntegerField(default=75),
        ),
    ]
