# Generated by Django 4.0.4 on 2022-05-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0016_term_insurance_p_maturity_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term_insurance',
            name='p_maturity_age',
            field=models.IntegerField(default=500),
        ),
    ]
