# Generated by Django 4.0.4 on 2022-06-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0018_term_insurance_p_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term_insurance',
            name='p_name',
            field=models.TextField(max_length=70),
        ),
    ]
