# Generated by Django 4.0.4 on 2022-06-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0019_alter_term_insurance_p_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term_insurance',
            name='p_name',
            field=models.CharField(max_length=70),
        ),
    ]
