# Generated by Django 4.0.4 on 2022-06-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0020_alter_term_insurance_p_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='term_insurance',
        ),
    ]
