# Generated by Django 4.0.4 on 2022-06-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0021_delete_term_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='term_insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insuor', models.CharField(max_length=50)),
                ('life_cover', models.PositiveIntegerField()),
                ('cover_till_age', models.PositiveIntegerField()),
                ('claim_settelment', models.IntegerField()),
                ('pay_monthly', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'term_insurance',
            },
        ),
    ]
