# Generated by Django 4.0.4 on 2022-06-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0023_alter_term_insurance_claim_settelment'),
    ]

    operations = [
        migrations.CreateModel(
            name='health_insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=50)),
                ('cover_amount', models.PositiveIntegerField()),
                ('policy_period', models.PositiveIntegerField()),
                ('pay_monthly', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'health_insurance',
            },
        ),
    ]
